<?php
namespace Softonic\DownloadApiInstance\Sdk\Exceptions;

/**
 * Ancestor of all exceptions of client api.
 *
 * Generated by SDK generator.
 *
 * @package Softonic\DownloadApiInstance\Sdk
 * @author Kyryl Sablin <kyryl.sablin@softonic.com>
 */
abstract class ApiException extends \Exception
{
}

