<?php
namespace Softonic\DownloadApiInstance\Sdk\Exceptions;

/**
 * Exception caused by invalid parameters or invalid method.
 *
 * Generated by SDK generator.
 *
 * @package Softonic\DownloadApiInstance\Sdk
 * @author Kyryl Sablin <kyryl.sablin@softonic.com>
 */
class BadRequestException extends ApiException
{
}

