<?php
namespace Softonic\DownloadApiInstance\Sdk\Exceptions;

/**
 * Exception caused by malformed response content but with good response code.
 *
 * Generated by SDK generator.
 *
 * @package Softonic\DownloadApiInstance\Sdk
 * @author Kyryl Sablin <kyryl.sablin@softonic.com>
 */
class MalformedResponseException extends ApiException
{
}

