<?php
namespace Softonic\DownloadApiInstance\Sdk\Exceptions;

/**
 * Api timeout exception.
 *
 * Generated by SDK generator.
 *
 * @package Softonic\DownloadApiInstance\Sdk
 * @author Kyryl Sablin <kyryl.sablin@softonic.com>
 */
class TimeoutException extends ApiException
{
}

