<?php
namespace Softonic\DownloadApiInstance\Sdk\Exceptions;

/**
 * All errors unhandled by other exceptions.
 *
 * Generated by SDK generator.
 *
 * @package Softonic\DownloadApiInstance\Sdk
 * @author Kyryl Sablin <kyryl.sablin@softonic.com>
 */
class UnexpectedResponseException extends ApiException
{
}

