<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
namespace Softonic\DownloadApiInstance\Sdk\Services\Files;

use Softonic\DownloadApiInstance\Sdk\APIClientInterface;

/**
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
class UrlsApi
{
    function __construct(APIClientInterface $api_client)
    {
        $this->api_client = $api_client;
    }

   

    /**
     * find
     * List of resources
     *
     * @param string $id_files SHA-1 hash that identifies a file
     * @param string $country The country from where the request is being done, used to sort download URL list
     * @param string $extra Associative array of parameters serialized and encoded in base64
     * @param integer $best Flag to get the best url instead of the whole list
     *
     * @return mixed
     */
    public function find($id_files, $country, $extra, $best)
    {

        //parse inputs
        $resource_path = "/files/{id_files}/urls";
        $resource_path = str_replace("{format}", "json", $resource_path);
        $method = "GET";

        $query_params = array();
        $header_params = array();
        $header_params['Accept'] = 'application/json';
        $header_params['Content-Type'] = 'application/json';

        if($id_files != null) {
             $resource_path = str_replace("{" . "id_files" . "}",
                $this->api_client->toPathValue($id_files), $resource_path);
        }
        if($country != null) {
            $query_params['country'] = $this->api_client->toQueryValue($country);
        }
        if($extra != null) {
            $query_params['extra'] = $this->api_client->toQueryValue($extra);
        }
        if($best != null) {
            $query_params['best'] = $this->api_client->toQueryValue($best);
        }
        if (!isset($data)) {
            $data = array();
        }
        $response = $this->api_client->callAPI($resource_path, $method,
                                              $query_params, $data,
                                              $header_params);


        if(!$response){
            return null;
        }

        return $response;


    }


}

