<?php
/**
 * FilesUrlsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\DownloadApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Download API
 *
 * Generated URLs with TTL for downloading binary files
 *
 * OpenAPI spec version: 2.36.0
 * Contact: admin@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\DownloadApiSdk;

use \Softonic\DownloadApiSdk\Configuration;
use \Softonic\DownloadApiSdk\ApiException;
use \Softonic\DownloadApiSdk\ObjectSerializer;

/**
 * FilesUrlsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\DownloadApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FilesUrlsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for findFileUrl
     *
     * List of FileUrls.
     *
     */
    public function testFindFileUrl()
    {
    }
}
